services:
    cloudflare:
        image: cloudflare/cloudflared:latest
        container_name: cloudflare-backup
        hostname: cloudflare-backup
        command:
            - tunnel
            - "run"
            - "--token"
            - "${CLOUDFLARE_TUNNEL_TOKEN}"
        env_file:
            - .env
        restart: unless-stopped
        volumes:
        - .config.yaml:/etc/cloudflared/config.yaml

    node_exporter:
        image: quay.io/prometheus/node-exporter:latest
        container_name: node_exporter
        ports:
          - 9100:9100
        command:
          - '--path.rootfs=/host'
        pid: host
        restart: unless-stopped
        volumes:
          - '/:/host:ro,rslave'
    
    cadvisor:
        image: gcr.io/cadvisor/cadvisor:latest
        container_name: cadvisor
        ports:
          - 8080:8080
        volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:ro
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
          - /dev/disk/:/dev/disk:ro
        devices:
          - /dev/kmsg
        privileged: true
        restart: unless-stopped